export const books = [
  {
    id: "f0b5d7f1-29e0-4e68-8b4e-b68f3ac5a0b6",
    name: "The Enchanted Forest",
    description: "A thrilling adventure through a mystical forest full of magical creatures and ancient secrets.",
    author: "Emily Thompson",
    publisher: "Starlight Publishing",
    price: "19,990",
    image: "/TempBook.png",
  },
  {
    id: "a7c6e88a-91c7-4d38-a61a-01356a4b4a23",
    name: "Mystery of the Lost City",
    description: "An exhilarating quest to uncover the hidden city of legends, packed with intrigue and peril.",
    author: "James Hunter",
    publisher: "Epic Reads",
    price: "24,500",
    image: "/TempBook.png",
  },
  {
    id: "b2d8f946-2f70-4b1e-8e9f-037ddc6632e5",
    name: "Journey Through Time",
    description: "A captivating journey that spans across different eras and civilizations, exploring the marvels of history.",
    author: "Sophia Lee",
    publisher: "History Press",
    price: "15,750",
    image: "/TempBook.png",
  },
  {
    id: "e8a69e8a-5074-4c4a-bb6c-29b68cfdf8f3",
    name: "Secrets of the Deep Sea",
    description: "Dive into the unknown depths of the ocean to discover lost treasures and enigmatic sea creatures.",
    author: "Oliver Stone",
    publisher: "Marine Tales",
    price: "22,000",
    image: "/TempBook.png",
  },
  {
    id: "c5d2a8f6-2d8e-4ef5-bdb0-08a637fc42ae",
    name: "The Last Kingdom",
    description: "An epic saga of a fallen kingdom and the brave heroes fighting to restore its former glory.",
    author: "Charlotte Green",
    publisher: "Kingdom Books",
    price: "29,990",
    image: "/TempBook.png",
  },
  {
    id: "d9b8e446-5b5a-49dc-9f7d-2fdbb6b0d76a",
    name: "The Hidden Sanctuary",
    description: "A riveting story of a secret sanctuary where magic and mystery intertwine, revealing hidden truths.",
    author: "Liam Wright",
    publisher: "Mystic Press",
    price: "18,450",
    image: "/TempBook.png",
  },
  {
    id: "e1d7f84a-bb56-47c3-bac9-1c3cbf892e67",
    name: "Echoes of the Past",
    description: "Unravel the echoes of history and uncover long-lost secrets that could change the course of the present.",
    author: "Ava Martinez",
    publisher: "Legacy Books",
    price: "21,800",
    image: "/TempBook.png",
  },
  {
    id: "f3a9b789-437a-414b-88e7-bc74565c1cf6",
    name: "The Time Traveler's Diary",
    description: "An extraordinary journey through time documented in a diary that holds the key to unraveling temporal mysteries.",
    author: "Ethan Brown",
    publisher: "Temporal Tales",
    price: "25,600",
    image: "/TempBook.png",
  },
  {
    id: "c0c37c77-8c21-4394-8a4b-3f4b95fbd4f7",
    name: "Whispers in the Dark",
    description: "A suspenseful thriller filled with dark secrets and eerie whispers that lead to a gripping climax.",
    author: "Isabella Johnson",
    publisher: "Shadow Press",
    price: "23,990",
    image: "/TempBook.png",
  },
  {
    id: "b5a5c9e0-7a0b-4d27-8d2a-4c934e8d4a0e",
    name: "Legends of the North",
    description: "Explore the legends and lore of the northern lands, where myths and reality blend into epic tales.",
    author: "Mason Smith",
    publisher: "Northern Lights Publishing",
    price: "27,500",
    image: "/TempBook.png",
  },
  {
    id: "f4d87d24-4468-45d2-9c4d-5c4cb7e831a1",
    name: "The Astral Navigator",
    description: "An interstellar voyage with a navigator who charts the stars and uncovers cosmic wonders and dangers.",
    author: "Olivia Anderson",
    publisher: "Galactic Books",
    price: "30,000",
    image: "/TempBook.png",
  },
];
